version: '3'
services:
    back:
        build:
            context: './back'
        command: 'node index'
        ports:
            - 3010:3010
        expose:
            - 3010
    front:
        build:
            context: './front'
        command: ['npm', 'start']
        ports:
            - 3000:3000
        tty: true
    nginx:
        build:
            context: './nginx'
        command: ['nginx', '-g', 'daemon off;']
        ports:
            - 80:80
        extra_hosts:
            - 'host.docker,internal:host-gateway'
        expose:
            - 80
